import '../css/style.css'
import '../css/header.css'
import '../css/modern-normalize.css'
// import './header.js'
import './footer.js'
import './returnButton.js'
import './dark_mode.js'
import './animations.js'
